### ISSUE TITLE
Does not work on Node >= v6.0.0

### ISSUE THREAD

**Issue by djdmbrwsk** [atdrago/negative#73]
```
Uncaught Exception:
Error: Module version mismatch. Expected 47, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at bindings (/Users/dan/dev/negative/dist/Negative-darwin-x64/Negative.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/dan/dev/negative/dist/Negative-darwin-x64/Negative.app/Contents/Resources/app.asar/node_modules/ref/lib/ref.js:5:47)
```

**Comment by atdrago** [comment]
Thanks! 👍 

I should add `engines` (and `os`) to the package.json to try to mitigate this.

**Comment by atdrago** [comment]
Looks like Electron is only compatible with v5.10.0 of Node right now.

See https://github.com/electron/electron/blob/master/.node-version#L1

I'll keep this issue open until this is resolved.

**Comment by djdmbrwsk** [comment]
👍
